apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-jwt-server
  labels:
    app: go-jwt-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-jwt-server
  template:
    metadata:
      labels:
        app: go-jwt-server
    spec:
      containers:
        - name: go-jwt-server
          image: localhost/go-jwt-server:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JWT_MASTER_KEY
              value: "qwertyuiopasdfghjklzxcvbnmqazwsx"
          volumeMounts:
            - name: app-config
              mountPath: /app/configs
      volumes:
        - name: app-config
          configMap:
            name: go-jwt-server-config